Задачи выполнены
DimonYarkin/repojs pull request #3
Opened 2021-04-06 15:21 UTC by DimonYarkin

2021-04-13 15:47 UTC, Om1X requested changes

2021-04-13 15:47 UTC, Om1X commented on lesson4/script.js
> +        goods: {},
это должен быть массив а не объект

2021-04-13 15:47 UTC, Om1X commented on lesson4/script.js
> +            }
соотвественно нужно переделать этот метод

2021-04-13 19:05 UTC, DimonYarkin commented on lesson4/script.js
> +        goods: {},
все исправлено

2021-04-13 19:06 UTC, DimonYarkin commented on lesson4/script.js
> +            }
все исправлено

2021-04-16 15:26 UTC, Om1X approved these changes

2021-04-16 19:51 UTC, merged